modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''修复 Colorwheel 在 Iris 下编译 Flywheel 嵌入式着色器时的兼容性问题，缓解 Create Aeronautics/Simulated 相关可视化导致的崩溃与显示异常。'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "iris"
type = "required"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "colorwheel"
type = "required"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "flywheel"
type = "required"
ordering = "AFTER"
side = "CLIENT"
